# Generated by Django 2.2.1 on 2019-05-05 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190505_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total_files',
            name='email',
        ),
        migrations.RemoveField(
            model_name='total_files',
            name='message',
        ),
        migrations.RemoveField(
            model_name='total_files',
            name='name',
        )
    ]
