# Generated by Django 2.2.1 on 2019-05-05 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190505_1956'),
    ]

    operations = [

        migrations.AddField(
            model_name='total_files',
            name='total_files',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
